name: Hyper-V VM Setup (Self-Hosted)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-hyperv-vm:
    runs-on: self-hosted 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Allow PowerShell Scripts
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

      - name: Verify Terraform Installation
        run: |
          terraform --version

      - name: Verify Python Installation
        run: |
          python --version
          pip install paramiko
          pip install flask request 

      - name: Initialize and Apply Terraform
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Get VM IP Address
        id: get-vm-ip
        working-directory: terraform
        run: |
          $vm_ip = terraform output -raw vm_ip
          echo "VM_IP=$vm_ip" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV

      - name: Install Dependencies on VM
        env:
          VM_IP: ${{ env.VM_IP }}
        run: python setup_vm.py